-- ============================================================
-- Supabase_13 — ระบบเงินสดนำส่ง (cash remittance)
-- รันใน Supabase → SQL Editor → New query → วาง → Run (รันซ้ำได้)
-- ============================================================

-- หมายเหตุ: หักเฉพาะค่าใช้จ่ายชนิด POS (เงินออกจากลิ้นชัก) — ไม่ต้องมีฟิลด์เพิ่ม

-- 1) ตารางรอบการนำส่งเงินสด
create table if not exists public.cash_remittance (
  id               bigint generated by default as identity primary key,
  period_start     date,
  period_end       date,
  cash_total       numeric default 0,     -- ยอดขายเงินสดรวมในรอบ (คำนวณ)
  expense_total    numeric default 0,     -- ค่าใช้จ่ายเงินสดในรอบ (คำนวณ)
  net_amount       numeric default 0,     -- ยอดนำส่งที่ระบบคำนวณ
  included_dates   jsonb,                 -- วันที่ปิดรอบที่นับรวม
  status           text default 'submitted',  -- submitted | confirmed | flagged
  submitted_by     text,
  submitted_amount numeric default 0,     -- ยอดที่นำส่งจริง (พนักงานกรอก)
  slip_url         text,
  submitted_at     timestamptz default now(),
  confirmed_by     text,
  confirmed_at     timestamptz,
  diff             numeric default 0,     -- submitted_amount − net_amount
  note             text,
  created_at       timestamptz default now()
);

-- 3) RLS: อ่าน/บันทึกการนำส่งได้ (ฝั่งพนักงาน) — การ "ยืนยันรับเงิน" ทำผ่าน Edge (service_role) เท่านั้น
alter table public.cash_remittance enable row level security;

drop policy if exists v2_sel_remit on public.cash_remittance;
create policy v2_sel_remit on public.cash_remittance for select to anon, authenticated using (true);

drop policy if exists v2_ins_remit on public.cash_remittance;
create policy v2_ins_remit on public.cash_remittance for insert to anon, authenticated with check (true);

-- (ไม่เปิด update/delete ให้ anon — การยืนยัน/แก้ทำผ่าน Edge Function ด้วย service_role)

-- 4) Storage bucket สลิปการนำส่ง (สาธารณะให้ดูรูปได้)
insert into storage.buckets (id, name, public) values ('remit-slips','remit-slips',true)
on conflict (id) do update set public = true;

drop policy if exists v2_remit_slip_upload on storage.objects;
create policy v2_remit_slip_upload on storage.objects for insert to anon, authenticated with check (bucket_id='remit-slips');
drop policy if exists v2_remit_slip_read on storage.objects;
create policy v2_remit_slip_read on storage.objects for select to anon, authenticated using (bucket_id='remit-slips');

select 'done' as status;
